#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
从 enrich_web2.py(66条) 与 enrich_notion.py(38条) 抽取已写入 Notion 的 BFC 内容,
合并去重后生成 src/agent-kb/webContent.ts (KbItem[]), 供导购助手(Worker + 前端本地引擎)检索。

用法:
  python gen_webcontent.py
输出:
  ../src/agent-kb/webContent.ts
"""
import ast, json, pathlib

HERE = pathlib.Path(__file__).resolve().parent
WEB2 = HERE / "enrich_web2.py"
NOTION1 = HERE / "enrich_notion.py"
OUT = HERE.parent / "src" / "agent-kb" / "webContent.ts"


def _eval(node):
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, ast.Dict):
        return {_eval(k): _eval(v) for k, v in zip(node.keys, node.values)}
    if isinstance(node, ast.List):
        return [_eval(e) for e in node.elts]
    if isinstance(node, ast.Tuple):
        return tuple(_eval(e) for e in node.elts)
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == "dict":
        return {kw.arg: _eval(kw.value) for kw in node.keywords}
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
        return -_eval(node.operand)
    raise ValueError(f"unsupported node: {node!r}")


def load_lists(path: pathlib.Path, names):
    tree = ast.parse(path.read_text(encoding="utf-8"))
    out = {}
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id in names:
                    out[t.id] = _eval(node.value)
    return out


def j(s: str) -> str:
    return json.dumps(s or "", ensure_ascii=False)


items = []          # list of dict(id, title, category, content, keywords)
seen = set()        # 去重(按 title 小写)


def add(title, category, content, keywords):
    key = (title or "").strip().lower()
    if key in seen:
        return
    seen.add(key)
    kid = f"wc-{len(items)+1:03d}"
    items.append({
        "id": kid,
        "title": title,
        "category": category,
        "content": content,
        "keywords": keywords,
    })


# ---------------- web2 批次(数据更全, 优先, 含电话/营业时间) ----------------
w2 = load_lists(WEB2, ["RESTAURANTS", "GUIDES", "EVENTS", "BRANDS"])

for e in w2["RESTAURANTS"]:
    avg = f"¥{e['avg']}" if e.get("avg") else "—"
    score = e.get("score") or "—"
    tel = e.get("tel") or "—"
    content = (f"菜系：{e['cuisine']}｜楼层：{e['floor']}｜评分：{score}｜人均：{avg}｜"
               f"电话：{tel}｜营业时间：{e.get('hours','—')}｜地址：{e.get('addr','—')}｜特色：{e.get('honor','')}")
    add(e["name"], "餐厅信息", content,
        [e["name"], e["cuisine"], "餐厅", "美食", "电话", "营业时间", e["floor"]])

for e in w2["GUIDES"]:
    content = f"类型：{e['typ']}｜地点：{e['place']}｜{e['content']}"
    add(e["title"], "打卡攻略", content,
        [e["title"], e["typ"], e["place"], "打卡", "机位", "出片", "拍照", "探店"])

for e in w2["EVENTS"]:
    content = f"时间：{e['when']}｜地点：{e['place']}｜{e['desc']}"
    add(e["name"], "活动", content,
        [e["name"], "活动", "展览", "打卡", "暑期", "近期", "市集", "演出", e["when"], e["place"]])

for e in w2["BRANDS"]:
    content = f"品类：{e['cat']}｜楼层：{e['floor']}｜特色：{e['feat']}"
    add(e["name"], "品牌导购", content,
        [e["name"], e["cat"], "品牌", "旗舰店", "买手", "购物", e["floor"]])

# ---------------- notion 首批(补艺术/宠物/夜生活/部分品牌) ----------------
n1 = load_lists(NOTION1, ["ENTRIES"])
CAT_MAP = {
    "美食餐厅": "餐厅信息",
    "艺术展览": "展览",
    "购物品牌": "品牌导购",
    "宠物友好": "宠物友好",
    "打卡机位": "打卡攻略",
    "夜生活": "夜生活",
}
for e in n1["ENTRIES"]:
    cat = CAT_MAP.get(e["cat"], "餐厅信息")
    avg = f"¥{e['avg']}" if e.get("avg") else "—"
    score = e.get("score") or "—"
    tel = e.get("tel") or "—"
    if e["cat"] == "美食餐厅":
        content = (f"菜系：美食餐厅｜位置：{e['loc']}｜评分：{score}｜人均：{avg}｜电话：{tel}｜"
                   f"推荐：{e['why']}｜标签：{'、'.join(e.get('tags', []))}")
        kws = [e["name"], "餐厅", "美食", "电话", "营业时间", e["loc"]] + e.get("tags", [])
    else:
        content = f"类别：{e['cat']}｜位置：{e['loc']}｜{e['why']}"
        kws = [e["name"], e["cat"], e["loc"]] + e.get("tags", [])
        if e["cat"] == "艺术展览":
            kws += ["展览", "艺术", "打卡"]
        elif e["cat"] == "宠物友好":
            kws += ["宠物", "撸猫", "狗狗", "萌宠"]
        elif e["cat"] == "夜生活":
            kws += ["酒吧", "夜生活", "lounge"]
        elif e["cat"] == "购物品牌":
            kws += ["品牌", "旗舰店", "买手", "购物"]
        elif e["cat"] == "打卡机位":
            kws += ["打卡", "机位", "出片", "拍照", "探店"]
    add(e["name"], cat, content, kws)


# ---------------- 写出 TS ----------------
lines = []
lines.append("// AUTO-GENERATED by notion-kb/gen_webcontent.py — 请勿手动编辑")
lines.append("// 数据来源: Notion「BFC知识库」(enrich_web2.py 66条 + enrich_notion.py 38条),")
lines.append("// 经公开网络检索(官网/腾讯地图/新闻攻略/小红书聚合)采集整理。")
lines.append("import type { KbItem } from './types'")
lines.append("")
lines.append("export const WEB_CONTENT: KbItem[] = [")
for it in items:
    lines.append("  {")
    lines.append(f"    id: {j(it['id'])},")
    lines.append(f"    title: {j(it['title'])},")
    lines.append(f"    category: {j(it['category'])},")
    lines.append(f"    content: {j(it['content'])},")
    lines.append(f"    keywords: [{', '.join(j(k) for k in it['keywords'])}],")
    lines.append("  },")
lines.append("]")
lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"[OK] 生成 {OUT}  共 {len(items)} 条 (去重后)")
